
namespace Beamable.Api.Autogenerated.Accounts
{
	using Beamable.Api.Autogenerated.Models;
	using Beamable.Common;
	using Beamable.Common.Content;
	using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
	using Method = Beamable.Common.Api.Method;

	public partial interface IAccountsApi
	{
	}
	public partial class AccountsApi : IAccountsApi
	{
		private IBeamableRequester _requester;
		public AccountsApi(IBeamableRequester requester)
		{
			this._requester = requester;
		}
	}
}
