
namespace Beamable.Api.Autogenerated.Announcements
{
	using Beamable.Api.Autogenerated.Models;
	using Beamable.Common;
	using Beamable.Common.Content;
	using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
	using Method = Beamable.Common.Api.Method;

	public partial interface IAnnouncementsApi
	{
	}
	public partial class AnnouncementsApi : IAnnouncementsApi
	{
		private IBeamableRequester _requester;
		public AnnouncementsApi(IBeamableRequester requester)
		{
			this._requester = requester;
		}
	}
}
