
namespace Beamable.Api.Autogenerated.Auth
{
	using Beamable.Api.Autogenerated.Models;
	using Beamable.Common;
	using Beamable.Common.Content;
	using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
	using Method = Beamable.Common.Api.Method;

	public partial interface IAuthApi
	{
	}
	public partial class AuthApi : IAuthApi
	{
		private IBeamableRequester _requester;
		public AuthApi(IBeamableRequester requester)
		{
			this._requester = requester;
		}
	}
}
