
namespace Beamable.Api.Autogenerated.Beamo
{
	using Beamable.Api.Autogenerated.Models;
	using Beamable.Common;
	using Beamable.Common.Content;
	using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
	using Method = Beamable.Common.Api.Method;

	public partial interface IBeamoApi
	{
		/// <param name="gsReq">The <see cref="GetMetricsUrlRequest"/> instance to use for the request</param>
		/// <returns>A promise containing the <see cref="GetSignedUrlResponse"/></returns>
		Promise<GetSignedUrlResponse> PostMetricsUrl(GetMetricsUrlRequest gsReq);
		/// <returns>A promise containing the <see cref="MicroserviceSecretResponse"/></returns>
		Promise<MicroserviceSecretResponse> GetMicroserviceSecret();
		/// <param name="endDate"></param>
		/// <param name="granularity"></param>
		/// <param name="period"></param>
		/// <param name="startDate"></param>
		/// <param name="storageObjectName"></param>
		/// <returns>A promise containing the <see cref="PerformanceResponse"/></returns>
		Promise<PerformanceResponse> GetStoragePerformance(string granularity, string storageObjectName, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> endDate, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> period, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> startDate);
		/// <param name="archived"></param>
		/// <param name="limit"></param>
		/// <param name="offset"></param>
		/// <returns>A promise containing the <see cref="GetManifestsResponse"/></returns>
		Promise<GetManifestsResponse> GetManifests([System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<bool> archived, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> limit, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> offset);
		/// <returns>A promise containing the <see cref="GetTemplatesResponse"/></returns>
		Promise<GetTemplatesResponse> GetTemplates();
		/// <param name="gsReq">The <see cref="GetLogsUrlRequest"/> instance to use for the request</param>
		/// <returns>A promise containing the <see cref="GetSignedUrlResponse"/></returns>
		Promise<GetSignedUrlResponse> PostLogsUrl(GetLogsUrlRequest gsReq);
		/// <returns>A promise containing the <see cref="GetLambdaURI"/></returns>
		Promise<GetLambdaURI> GetUploadAPI();
		/// <returns>A promise containing the <see cref="GetStatusResponse"/></returns>
		Promise<GetStatusResponse> GetStatus();
		/// <param name="archived"></param>
		/// <returns>A promise containing the <see cref="GetCurrentManifestResponse"/></returns>
		Promise<GetCurrentManifestResponse> GetManifestCurrent([System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<bool> archived);
		/// <param name="gsReq">The <see cref="PullBeamoManifestRequest"/> instance to use for the request</param>
		/// <returns>A promise containing the <see cref="ManifestChecksums"/></returns>
		Promise<ManifestChecksums> PostManifestPull(PullBeamoManifestRequest gsReq);
		/// <returns>A promise containing the <see cref="GetElasticContainerRegistryURI"/></returns>
		Promise<GetElasticContainerRegistryURI> GetRegistry();
		/// <returns>A promise containing the <see cref="EmptyResponse"/></returns>
		Promise<EmptyResponse> PostManifestDeploy();
		/// <returns>A promise containing the <see cref="ConnectionString"/></returns>
		Promise<ConnectionString> GetStorageConnection();
		/// <param name="archived"></param>
		/// <param name="id"></param>
		/// <returns>A promise containing the <see cref="GetManifestResponse"/></returns>
		Promise<GetManifestResponse> GetManifest(string id, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<bool> archived);
		/// <param name="gsReq">The <see cref="PostManifestRequest"/> instance to use for the request</param>
		/// <returns>A promise containing the <see cref="PostManifestResponse"/></returns>
		Promise<PostManifestResponse> PostManifest(PostManifestRequest gsReq);
	}
	public partial class BeamoApi : IBeamoApi
	{
		/// <param name="gsReq">The <see cref="GetMetricsUrlRequest"/> instance to use for the request</param>
		/// <returns>A promise containing the <see cref="GetSignedUrlResponse"/></returns>
		public virtual Promise<GetSignedUrlResponse> PostMetricsUrl(GetMetricsUrlRequest gsReq)
		{
			string gsUrl = "/basic/beamo/metricsUrl";
			// make the request and return the result
			return _requester.Request<GetSignedUrlResponse>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), true, Beamable.Serialization.JsonSerializable.FromJson<GetSignedUrlResponse>);
		}
		/// <returns>A promise containing the <see cref="MicroserviceSecretResponse"/></returns>
		public virtual Promise<MicroserviceSecretResponse> GetMicroserviceSecret()
		{
			string gsUrl = "/basic/beamo/microservice/secret";
			// make the request and return the result
			return _requester.Request<MicroserviceSecretResponse>(Method.GET, gsUrl, default(object), true, Beamable.Serialization.JsonSerializable.FromJson<MicroserviceSecretResponse>);
		}
		/// <param name="endDate"></param>
		/// <param name="granularity"></param>
		/// <param name="period"></param>
		/// <param name="startDate"></param>
		/// <param name="storageObjectName"></param>
		/// <returns>A promise containing the <see cref="PerformanceResponse"/></returns>
		public virtual Promise<PerformanceResponse> GetStoragePerformance(string granularity, string storageObjectName, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> endDate, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> period, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> startDate)
		{
			string gsUrl = "/basic/beamo/storage/performance";
			string gsQuery = "?";
			System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
			if (((endDate != default(OptionalString))
						&& endDate.HasValue))
			{
				gsQueries.Add(string.Concat("endDate=", endDate.Value.ToString()));
			}
			gsQueries.Add(string.Concat("storageObjectName=", storageObjectName.ToString()));
			gsQueries.Add(string.Concat("granularity=", granularity.ToString()));
			if (((startDate != default(OptionalString))
						&& startDate.HasValue))
			{
				gsQueries.Add(string.Concat("startDate=", startDate.Value.ToString()));
			}
			if (((period != default(OptionalString))
						&& period.HasValue))
			{
				gsQueries.Add(string.Concat("period=", period.Value.ToString()));
			}
			gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
			gsUrl = string.Concat(gsUrl, gsQuery);
			// make the request and return the result
			return _requester.Request<PerformanceResponse>(Method.GET, gsUrl, default(object), true, Beamable.Serialization.JsonSerializable.FromJson<PerformanceResponse>);
		}
		/// <param name="archived"></param>
		/// <param name="limit"></param>
		/// <param name="offset"></param>
		/// <returns>A promise containing the <see cref="GetManifestsResponse"/></returns>
		public virtual Promise<GetManifestsResponse> GetManifests([System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<bool> archived, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> limit, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> offset)
		{
			string gsUrl = "/basic/beamo/manifests";
			string gsQuery = "?";
			System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
			if (((offset != default(OptionalInt))
						&& offset.HasValue))
			{
				gsQueries.Add(string.Concat("offset=", offset.Value.ToString()));
			}
			if (((limit != default(OptionalInt))
						&& limit.HasValue))
			{
				gsQueries.Add(string.Concat("limit=", limit.Value.ToString()));
			}
			if (((archived != default(OptionalBool))
						&& archived.HasValue))
			{
				gsQueries.Add(string.Concat("archived=", archived.Value.ToString()));
			}
			gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
			gsUrl = string.Concat(gsUrl, gsQuery);
			// make the request and return the result
			return _requester.Request<GetManifestsResponse>(Method.GET, gsUrl, default(object), true, Beamable.Serialization.JsonSerializable.FromJson<GetManifestsResponse>);
		}
		/// <returns>A promise containing the <see cref="GetTemplatesResponse"/></returns>
		public virtual Promise<GetTemplatesResponse> GetTemplates()
		{
			string gsUrl = "/basic/beamo/templates";
			// make the request and return the result
			return _requester.Request<GetTemplatesResponse>(Method.GET, gsUrl, default(object), true, Beamable.Serialization.JsonSerializable.FromJson<GetTemplatesResponse>);
		}
		/// <param name="gsReq">The <see cref="GetLogsUrlRequest"/> instance to use for the request</param>
		/// <returns>A promise containing the <see cref="GetSignedUrlResponse"/></returns>
		public virtual Promise<GetSignedUrlResponse> PostLogsUrl(GetLogsUrlRequest gsReq)
		{
			string gsUrl = "/basic/beamo/logsUrl";
			// make the request and return the result
			return _requester.Request<GetSignedUrlResponse>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), true, Beamable.Serialization.JsonSerializable.FromJson<GetSignedUrlResponse>);
		}
		/// <returns>A promise containing the <see cref="GetLambdaURI"/></returns>
		public virtual Promise<GetLambdaURI> GetUploadAPI()
		{
			string gsUrl = "/basic/beamo/uploadAPI";
			// make the request and return the result
			return _requester.Request<GetLambdaURI>(Method.GET, gsUrl, default(object), true, Beamable.Serialization.JsonSerializable.FromJson<GetLambdaURI>);
		}
		/// <returns>A promise containing the <see cref="GetStatusResponse"/></returns>
		public virtual Promise<GetStatusResponse> GetStatus()
		{
			string gsUrl = "/basic/beamo/status";
			// make the request and return the result
			return _requester.Request<GetStatusResponse>(Method.GET, gsUrl, default(object), true, Beamable.Serialization.JsonSerializable.FromJson<GetStatusResponse>);
		}
		/// <param name="archived"></param>
		/// <returns>A promise containing the <see cref="GetCurrentManifestResponse"/></returns>
		public virtual Promise<GetCurrentManifestResponse> GetManifestCurrent([System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<bool> archived)
		{
			string gsUrl = "/basic/beamo/manifest/current";
			string gsQuery = "?";
			System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
			if (((archived != default(OptionalBool))
						&& archived.HasValue))
			{
				gsQueries.Add(string.Concat("archived=", archived.Value.ToString()));
			}
			gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
			gsUrl = string.Concat(gsUrl, gsQuery);
			// make the request and return the result
			return _requester.Request<GetCurrentManifestResponse>(Method.GET, gsUrl, default(object), true, Beamable.Serialization.JsonSerializable.FromJson<GetCurrentManifestResponse>);
		}
		/// <param name="gsReq">The <see cref="PullBeamoManifestRequest"/> instance to use for the request</param>
		/// <returns>A promise containing the <see cref="ManifestChecksums"/></returns>
		public virtual Promise<ManifestChecksums> PostManifestPull(PullBeamoManifestRequest gsReq)
		{
			string gsUrl = "/basic/beamo/manifest/pull";
			// make the request and return the result
			return _requester.Request<ManifestChecksums>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), true, Beamable.Serialization.JsonSerializable.FromJson<ManifestChecksums>);
		}
		/// <returns>A promise containing the <see cref="GetElasticContainerRegistryURI"/></returns>
		public virtual Promise<GetElasticContainerRegistryURI> GetRegistry()
		{
			string gsUrl = "/basic/beamo/registry";
			// make the request and return the result
			return _requester.Request<GetElasticContainerRegistryURI>(Method.GET, gsUrl, default(object), true, Beamable.Serialization.JsonSerializable.FromJson<GetElasticContainerRegistryURI>);
		}
		/// <returns>A promise containing the <see cref="EmptyResponse"/></returns>
		public virtual Promise<EmptyResponse> PostManifestDeploy()
		{
			string gsUrl = "/basic/beamo/manifest/deploy";
			// make the request and return the result
			return _requester.Request<EmptyResponse>(Method.POST, gsUrl, default(object), true, Beamable.Serialization.JsonSerializable.FromJson<EmptyResponse>);
		}
		/// <returns>A promise containing the <see cref="ConnectionString"/></returns>
		public virtual Promise<ConnectionString> GetStorageConnection()
		{
			string gsUrl = "/basic/beamo/storage/connection";
			// make the request and return the result
			return _requester.Request<ConnectionString>(Method.GET, gsUrl, default(object), true, Beamable.Serialization.JsonSerializable.FromJson<ConnectionString>);
		}
		/// <param name="archived"></param>
		/// <param name="id"></param>
		/// <returns>A promise containing the <see cref="GetManifestResponse"/></returns>
		public virtual Promise<GetManifestResponse> GetManifest(string id, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<bool> archived)
		{
			string gsUrl = "/basic/beamo/manifest";
			string gsQuery = "?";
			System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
			gsQueries.Add(string.Concat("id=", id.ToString()));
			if (((archived != default(OptionalBool))
						&& archived.HasValue))
			{
				gsQueries.Add(string.Concat("archived=", archived.Value.ToString()));
			}
			gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
			gsUrl = string.Concat(gsUrl, gsQuery);
			// make the request and return the result
			return _requester.Request<GetManifestResponse>(Method.GET, gsUrl, default(object), true, Beamable.Serialization.JsonSerializable.FromJson<GetManifestResponse>);
		}
		/// <param name="gsReq">The <see cref="PostManifestRequest"/> instance to use for the request</param>
		/// <returns>A promise containing the <see cref="PostManifestResponse"/></returns>
		public virtual Promise<PostManifestResponse> PostManifest(PostManifestRequest gsReq)
		{
			string gsUrl = "/basic/beamo/manifest";
			// make the request and return the result
			return _requester.Request<PostManifestResponse>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), true, Beamable.Serialization.JsonSerializable.FromJson<PostManifestResponse>);
		}
	}
}
