
namespace Beamable.Api.Autogenerated.Chatv2
{
	using Beamable.Api.Autogenerated.Models;
	using Beamable.Common;
	using Beamable.Common.Content;
	using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
	using Method = Beamable.Common.Api.Method;

	public partial interface IChatv2Api
	{
	}
	public partial class Chatv2Api : IChatv2Api
	{
		private IBeamableRequester _requester;
		public Chatv2Api(IBeamableRequester requester)
		{
			this._requester = requester;
		}
	}
}
