
namespace Beamable.Api.Autogenerated.Commerce
{
	using Beamable.Api.Autogenerated.Models;
	using Beamable.Common;
	using Beamable.Common.Content;
	using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
	using Method = Beamable.Common.Api.Method;

	public partial interface ICommerceApi
	{
	}
	public partial class CommerceApi : ICommerceApi
	{
		private IBeamableRequester _requester;
		public CommerceApi(IBeamableRequester requester)
		{
			this._requester = requester;
		}
	}
}
