
namespace Beamable.Api.Autogenerated.Events
{
	using Beamable.Api.Autogenerated.Models;
	using Beamable.Common;
	using Beamable.Common.Content;
	using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
	using Method = Beamable.Common.Api.Method;

	public partial interface IEventsApi
	{
	}
	public partial class EventsApi : IEventsApi
	{
		private IBeamableRequester _requester;
		public EventsApi(IBeamableRequester requester)
		{
			this._requester = requester;
		}
	}
}
