
namespace Beamable.Api.Autogenerated.GroupUsers
{
	using Beamable.Api.Autogenerated.Models;
	using Beamable.Common;
	using Beamable.Common.Content;
	using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
	using Method = Beamable.Common.Api.Method;

	public partial interface IGroupUsersApi
	{
	}
	public partial class GroupUsersApi : IGroupUsersApi
	{
		private IBeamableRequester _requester;
		public GroupUsersApi(IBeamableRequester requester)
		{
			this._requester = requester;
		}
	}
}
