
namespace Beamable.Api.Autogenerated.Inventory
{
	using Beamable.Api.Autogenerated.Models;
	using Beamable.Common;
	using Beamable.Common.Content;
	using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
	using Method = Beamable.Common.Api.Method;

	public partial interface IInventoryApi
	{
	}
	public partial class InventoryApi : IInventoryApi
	{
		private IBeamableRequester _requester;
		public InventoryApi(IBeamableRequester requester)
		{
			this._requester = requester;
		}
	}
}
