
namespace Beamable.Api.Autogenerated.Mail
{
	using Beamable.Api.Autogenerated.Models;
	using Beamable.Common;
	using Beamable.Common.Content;
	using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
	using Method = Beamable.Common.Api.Method;

	public partial interface IMailApi
	{
		/// <param name="mid"></param>
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="MailResponse"/></returns>
		Promise<MailResponse> ObjectGetDetail(long mid, long objectId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="ListMailCategoriesResponse"/></returns>
		Promise<ListMailCategoriesResponse> ObjectGetCategories(long objectId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="gsReq">The <see cref="MailSearchRequest"/> instance to use for the request</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="MailSearchResponse"/></returns>
		Promise<MailSearchResponse> ObjectPostSearch(long objectId, MailSearchRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="gsReq">The <see cref="BulkSendMailRequest"/> instance to use for the request</param>
		/// <returns>A promise containing the <see cref="MailSuccessResponse"/></returns>
		Promise<MailSuccessResponse> ObjectPostBulk(long objectId, BulkSendMailRequest gsReq);
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="gsReq">The <see cref="BulkUpdateMailObjectRequest"/> instance to use for the request</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="MailSuccessResponse"/></returns>
		Promise<MailSuccessResponse> ObjectPutBulk(long objectId, BulkUpdateMailObjectRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="gsReq">The <see cref="AcceptMultipleAttachments"/> instance to use for the request</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="MailSuccessResponse"/></returns>
		Promise<MailSuccessResponse> ObjectPutAcceptMany(long objectId, AcceptMultipleAttachments gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="MailQueryResponse"/></returns>
		Promise<MailQueryResponse> ObjectGet(long objectId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="gsReq">The <see cref="SendMailObjectRequest"/> instance to use for the request</param>
		/// <returns>A promise containing the <see cref="SendMailResponse"/></returns>
		Promise<SendMailResponse> ObjectPost(long objectId, SendMailObjectRequest gsReq);
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="gsReq">The <see cref="UpdateMailRequest"/> instance to use for the request</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="MailSuccessResponse"/></returns>
		Promise<MailSuccessResponse> ObjectPut(long objectId, UpdateMailRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
	}
	public partial class MailApi : IMailApi
	{
		/// <param name="mid"></param>
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="MailResponse"/></returns>
		public virtual Promise<MailResponse> ObjectGetDetail(long mid, long objectId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
		{
			string gsUrl = "/object/mail/{objectId}/detail";
			gsUrl = gsUrl.Replace("{objectId}", objectId.ToString());
			string gsQuery = "?";
			System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
			gsQueries.Add(string.Concat("mid=", mid.ToString()));
			gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
			gsUrl = string.Concat(gsUrl, gsQuery);
			// make the request and return the result
			return _requester.Request<MailResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, Beamable.Serialization.JsonSerializable.FromJson<MailResponse>);
		}
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="ListMailCategoriesResponse"/></returns>
		public virtual Promise<ListMailCategoriesResponse> ObjectGetCategories(long objectId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
		{
			string gsUrl = "/object/mail/{objectId}/categories";
			gsUrl = gsUrl.Replace("{objectId}", objectId.ToString());
			// make the request and return the result
			return _requester.Request<ListMailCategoriesResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, Beamable.Serialization.JsonSerializable.FromJson<ListMailCategoriesResponse>);
		}
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="gsReq">The <see cref="MailSearchRequest"/> instance to use for the request</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="MailSearchResponse"/></returns>
		public virtual Promise<MailSearchResponse> ObjectPostSearch(long objectId, MailSearchRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
		{
			string gsUrl = "/object/mail/{objectId}/search";
			gsUrl = gsUrl.Replace("{objectId}", objectId.ToString());
			// make the request and return the result
			return _requester.Request<MailSearchResponse>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, Beamable.Serialization.JsonSerializable.FromJson<MailSearchResponse>);
		}
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="gsReq">The <see cref="BulkSendMailRequest"/> instance to use for the request</param>
		/// <returns>A promise containing the <see cref="MailSuccessResponse"/></returns>
		public virtual Promise<MailSuccessResponse> ObjectPostBulk(long objectId, BulkSendMailRequest gsReq)
		{
			string gsUrl = "/object/mail/{objectId}/bulk";
			gsUrl = gsUrl.Replace("{objectId}", objectId.ToString());
			// make the request and return the result
			return _requester.Request<MailSuccessResponse>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), true, Beamable.Serialization.JsonSerializable.FromJson<MailSuccessResponse>);
		}
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="gsReq">The <see cref="BulkUpdateMailObjectRequest"/> instance to use for the request</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="MailSuccessResponse"/></returns>
		public virtual Promise<MailSuccessResponse> ObjectPutBulk(long objectId, BulkUpdateMailObjectRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
		{
			string gsUrl = "/object/mail/{objectId}/bulk";
			gsUrl = gsUrl.Replace("{objectId}", objectId.ToString());
			// make the request and return the result
			return _requester.Request<MailSuccessResponse>(Method.PUT, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, Beamable.Serialization.JsonSerializable.FromJson<MailSuccessResponse>);
		}
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="gsReq">The <see cref="AcceptMultipleAttachments"/> instance to use for the request</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="MailSuccessResponse"/></returns>
		public virtual Promise<MailSuccessResponse> ObjectPutAcceptMany(long objectId, AcceptMultipleAttachments gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
		{
			string gsUrl = "/object/mail/{objectId}/accept/many";
			gsUrl = gsUrl.Replace("{objectId}", objectId.ToString());
			// make the request and return the result
			return _requester.Request<MailSuccessResponse>(Method.PUT, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, Beamable.Serialization.JsonSerializable.FromJson<MailSuccessResponse>);
		}
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="MailQueryResponse"/></returns>
		public virtual Promise<MailQueryResponse> ObjectGet(long objectId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
		{
			string gsUrl = "/object/mail/{objectId}/";
			gsUrl = gsUrl.Replace("{objectId}", objectId.ToString());
			// make the request and return the result
			return _requester.Request<MailQueryResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, Beamable.Serialization.JsonSerializable.FromJson<MailQueryResponse>);
		}
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="gsReq">The <see cref="SendMailObjectRequest"/> instance to use for the request</param>
		/// <returns>A promise containing the <see cref="SendMailResponse"/></returns>
		public virtual Promise<SendMailResponse> ObjectPost(long objectId, SendMailObjectRequest gsReq)
		{
			string gsUrl = "/object/mail/{objectId}/";
			gsUrl = gsUrl.Replace("{objectId}", objectId.ToString());
			// make the request and return the result
			return _requester.Request<SendMailResponse>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), true, Beamable.Serialization.JsonSerializable.FromJson<SendMailResponse>);
		}
		/// <param name="objectId">Gamertag of the player.Underlying objectId type is integer in format int64.</param>
		/// <param name="gsReq">The <see cref="UpdateMailRequest"/> instance to use for the request</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="MailSuccessResponse"/></returns>
		public virtual Promise<MailSuccessResponse> ObjectPut(long objectId, UpdateMailRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
		{
			string gsUrl = "/object/mail/{objectId}/";
			gsUrl = gsUrl.Replace("{objectId}", objectId.ToString());
			// make the request and return the result
			return _requester.Request<MailSuccessResponse>(Method.PUT, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, Beamable.Serialization.JsonSerializable.FromJson<MailSuccessResponse>);
		}
	}
}
