
namespace Beamable.Api.Autogenerated.Notification
{
	using Beamable.Api.Autogenerated.Models;
	using Beamable.Common;
	using Beamable.Common.Content;
	using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
	using Method = Beamable.Common.Api.Method;

	public partial interface INotificationApi
	{
	}
	public partial class NotificationApi : INotificationApi
	{
		private IBeamableRequester _requester;
		public NotificationApi(IBeamableRequester requester)
		{
			this._requester = requester;
		}
	}
}
