
namespace Beamable.Api.Autogenerated.Push
{
	using Beamable.Api.Autogenerated.Models;
	using Beamable.Common;
	using Beamable.Common.Content;
	using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
	using Method = Beamable.Common.Api.Method;

	public partial interface IPushApi
	{
	}
	public partial class PushApi : IPushApi
	{
		private IBeamableRequester _requester;
		public PushApi(IBeamableRequester requester)
		{
			this._requester = requester;
		}
	}
}
