
namespace Beamable.Api.Autogenerated.Social
{
	using Beamable.Api.Autogenerated.Models;
	using Beamable.Common;
	using Beamable.Common.Content;
	using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
	using Method = Beamable.Common.Api.Method;

	public partial interface ISocialApi
	{
	}
	public partial class SocialApi : ISocialApi
	{
		private IBeamableRequester _requester;
		public SocialApi(IBeamableRequester requester)
		{
			this._requester = requester;
		}
	}
}
