
namespace Beamable.Api.Autogenerated.Stats
{
	using Beamable.Api.Autogenerated.Models;
	using Beamable.Common;
	using Beamable.Common.Content;
	using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
	using Method = Beamable.Common.Api.Method;

	public partial interface IStatsApi
	{
		/// <param name="objectId">Format: domain.visibility.type.gamerTag</param>
		/// <param name="gsReq">The <see cref="StatUpdateRequestStringListFormat"/> instance to use for the request</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="EmptyResponse"/></returns>
		Promise<EmptyResponse> ObjectPostClientStringlist(string objectId, StatUpdateRequestStringListFormat gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
		/// <param name="objectId">Format: domain.visibility.type.gamerTag</param>
		/// <param name="stats"></param>
		/// <returns>A promise containing the <see cref="StatsResponse"/></returns>
		Promise<StatsResponse> ObjectGet(string objectId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> stats);
		/// <param name="objectId">Format: domain.visibility.type.gamerTag</param>
		/// <param name="gsReq">The <see cref="StatUpdateRequest"/> instance to use for the request</param>
		/// <returns>A promise containing the <see cref="EmptyResponse"/></returns>
		Promise<EmptyResponse> ObjectPost(string objectId, StatUpdateRequest gsReq);
		/// <param name="objectId">Format: domain.visibility.type.gamerTag</param>
		/// <param name="gsReq">The <see cref="StatRequest"/> instance to use for the request</param>
		/// <returns>A promise containing the <see cref="EmptyResponse"/></returns>
		Promise<EmptyResponse> ObjectDelete(string objectId, StatRequest gsReq);
		/// <param name="objectId">Format: domain.visibility.type.gamerTag</param>
		/// <param name="stats"></param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="StatsResponse"/></returns>
		Promise<StatsResponse> ObjectGetClient(string objectId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> stats, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
		/// <param name="objectId">Format: domain.visibility.type.gamerTag</param>
		/// <param name="gsReq">The <see cref="StatUpdateRequest"/> instance to use for the request</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="EmptyResponse"/></returns>
		Promise<EmptyResponse> ObjectPostClient(string objectId, StatUpdateRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
	}
	public partial class StatsApi : IStatsApi
	{
		/// <param name="objectId">Format: domain.visibility.type.gamerTag</param>
		/// <param name="gsReq">The <see cref="StatUpdateRequestStringListFormat"/> instance to use for the request</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="EmptyResponse"/></returns>
		public virtual Promise<EmptyResponse> ObjectPostClientStringlist(string objectId, StatUpdateRequestStringListFormat gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
		{
			string gsUrl = "/object/stats/{objectId}/client/stringlist";
			gsUrl = gsUrl.Replace("{objectId}", objectId.ToString());
			// make the request and return the result
			return _requester.Request<EmptyResponse>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, Beamable.Serialization.JsonSerializable.FromJson<EmptyResponse>);
		}
		/// <param name="objectId">Format: domain.visibility.type.gamerTag</param>
		/// <param name="stats"></param>
		/// <returns>A promise containing the <see cref="StatsResponse"/></returns>
		public virtual Promise<StatsResponse> ObjectGet(string objectId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> stats)
		{
			string gsUrl = "/object/stats/{objectId}/";
			gsUrl = gsUrl.Replace("{objectId}", objectId.ToString());
			string gsQuery = "?";
			System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
			if (((stats != default(OptionalString))
						&& stats.HasValue))
			{
				gsQueries.Add(string.Concat("stats=", stats.Value.ToString()));
			}
			gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
			gsUrl = string.Concat(gsUrl, gsQuery);
			// make the request and return the result
			return _requester.Request<StatsResponse>(Method.GET, gsUrl, default(object), true, Beamable.Serialization.JsonSerializable.FromJson<StatsResponse>);
		}
		/// <param name="objectId">Format: domain.visibility.type.gamerTag</param>
		/// <param name="gsReq">The <see cref="StatUpdateRequest"/> instance to use for the request</param>
		/// <returns>A promise containing the <see cref="EmptyResponse"/></returns>
		public virtual Promise<EmptyResponse> ObjectPost(string objectId, StatUpdateRequest gsReq)
		{
			string gsUrl = "/object/stats/{objectId}/";
			gsUrl = gsUrl.Replace("{objectId}", objectId.ToString());
			// make the request and return the result
			return _requester.Request<EmptyResponse>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), true, Beamable.Serialization.JsonSerializable.FromJson<EmptyResponse>);
		}
		/// <param name="objectId">Format: domain.visibility.type.gamerTag</param>
		/// <param name="gsReq">The <see cref="StatRequest"/> instance to use for the request</param>
		/// <returns>A promise containing the <see cref="EmptyResponse"/></returns>
		public virtual Promise<EmptyResponse> ObjectDelete(string objectId, StatRequest gsReq)
		{
			string gsUrl = "/object/stats/{objectId}/";
			gsUrl = gsUrl.Replace("{objectId}", objectId.ToString());
			// make the request and return the result
			return _requester.Request<EmptyResponse>(Method.DELETE, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), true, Beamable.Serialization.JsonSerializable.FromJson<EmptyResponse>);
		}
		/// <param name="objectId">Format: domain.visibility.type.gamerTag</param>
		/// <param name="stats"></param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="StatsResponse"/></returns>
		public virtual Promise<StatsResponse> ObjectGetClient(string objectId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)][System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> stats, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
		{
			string gsUrl = "/object/stats/{objectId}/client";
			gsUrl = gsUrl.Replace("{objectId}", objectId.ToString());
			string gsQuery = "?";
			System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
			if (((stats != default(OptionalString))
						&& stats.HasValue))
			{
				gsQueries.Add(string.Concat("stats=", stats.Value.ToString()));
			}
			gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
			gsUrl = string.Concat(gsUrl, gsQuery);
			// make the request and return the result
			return _requester.Request<StatsResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, Beamable.Serialization.JsonSerializable.FromJson<StatsResponse>);
		}
		/// <param name="objectId">Format: domain.visibility.type.gamerTag</param>
		/// <param name="gsReq">The <see cref="StatUpdateRequest"/> instance to use for the request</param>
		/// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
		/// <returns>A promise containing the <see cref="EmptyResponse"/></returns>
		public virtual Promise<EmptyResponse> ObjectPostClient(string objectId, StatUpdateRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)][System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
		{
			string gsUrl = "/object/stats/{objectId}/client";
			gsUrl = gsUrl.Replace("{objectId}", objectId.ToString());
			// make the request and return the result
			return _requester.Request<EmptyResponse>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, Beamable.Serialization.JsonSerializable.FromJson<EmptyResponse>);
		}
	}
}
