
namespace Beamable.Api.Autogenerated.Stats
{
	using Beamable.Api.Autogenerated.Models;
	using Beamable.Common;
	using Beamable.Common.Content;
	using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
	using Method = Beamable.Common.Api.Method;

	public partial interface IStatsApi
	{
	}
	public partial class StatsApi : IStatsApi
	{
		private IBeamableRequester _requester;
		public StatsApi(IBeamableRequester requester)
		{
			this._requester = requester;
		}
	}
}
