
namespace Beamable.Api.Autogenerated.Tournaments
{
	using Beamable.Api.Autogenerated.Models;
	using Beamable.Common;
	using Beamable.Common.Content;
	using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
	using Method = Beamable.Common.Api.Method;

	public partial interface ITournamentsApi
	{
	}
	public partial class TournamentsApi : ITournamentsApi
	{
		private IBeamableRequester _requester;
		public TournamentsApi(IBeamableRequester requester)
		{
			this._requester = requester;
		}
	}
}
